Download dataset yang ingin diproses

In [1]:
!gdown 1ClaVQVepWcrw4dBesxMvoVwSdmL1THVW

Downloading...
From: https://drive.google.com/uc?id=1ClaVQVepWcrw4dBesxMvoVwSdmL1THVW
To: /content/Food Detection.v2i.yolo26.zip
100% 17.5M/17.5M [00:00<00:00, 105MB/s]

In [2]:
!gdown 1skrVBHdY0fhWKdi2zgGe1CyOmvx_7uQ2

Downloading...
From (original): https://drive.google.com/uc?id=1skrVBHdY0fhWKdi2zgGe1CyOmvx_7uQ2
From (redirected): https://drive.google.com/uc?id=1skrVBHdY0fhWKdi2zgGe1CyOmvx_7uQ2&confirm=t&uuid=24fcbdc1-0f18-4ba1-9548-045ea45d1db2
To: /content/Food_Detection_Project.v19i.yolo26.zip
100% 314M/314M [00:06<00:00, 50.2MB/s]

In [1]:
!pip install pyyaml wandb

Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (6.0.3)
Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (0.25.0)
Requirement already satisfied: click>=8.0.1 in /usr/local/lib/python3.12/dist-packages (from wandb) (8.3.1)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (3.1.46)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from wandb) (26.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb) (4.9.2)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (5.29.6)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.12.3)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.53.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/dist-packages (from wandb) (4.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->wandb) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2026.1.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)

In [2]:
!apt-get install unzip

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
unzip is already the newest version (6.0-26ubuntu3.2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

In [3]:
!mkdir '/content/dataset'

Unzip ke folder /dataset

In [7]:
!unzip -d "/content/dataset/Food Detection.v2i.yolo26" "/content/Food Detection.v2i.yolo26.zip"

Archive:  /content/Food Detection.v2i.yolo26.zip
  inflating: /content/dataset/Food Detection.v2i.yolo26/README.dataset.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/README.roboflow.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/data.yaml
   creating: /content/dataset/Food Detection.v2i.yolo26/test/
   creating: /content/dataset/Food Detection.v2i.yolo26/test/images/
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/1028_191030_0004_jpg.rf.3f6884ec99e0e58d7b3947b7f6efa5b6.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/1028_191030_0039_jpg.rf.5dbc2837eae3e82740cb39d014b8d991.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/1028_191030_0068_jpg.rf.e8132a3cffab2d6df1c2996c4d73610e.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/1028_191030_0083_jpg.rf.53f8d9917663bd6331f1d1259c7bbc91.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/1028_191030_0092_jpg.rf.09d5c251d283269bb2e7ebfa279773de.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/1030_191030_0010_jpg.rf.982fb28e9b61458b3d57c8e6a891d7b9.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/1031_191103_0039_jpg.rf.040cf89743c5ec91477504b6da2dd9e5.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/1031_191103_0044_jpg.rf.22da80263c4f59716e21c22ab57237ff.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/8_jpg.rf.02a6950c1db69427361979acd1c527fc.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/IMG_4169_jpg.rf.dc4facf39573309af006fa9debfe38f0.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/IMG_4225_jpg.rf.6f4c194dbdfb39bf47b4e26720019b33.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/S__184819718_jpg.rf.dbdfee206092837c81a7b8d370c1103b.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/plate-220427-125120_jpg.rf.803af99ca069e3a5430739f083b9b11b.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/plate-220427-125306_jpg.rf.d1533144a79fa0779bcb3616ac502913.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/plate-220428-123237_jpg.rf.fb43d896e3031671d73f3eaa40f93bdb.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/plate-220428-124823_jpg.rf.2dd1ecdc445ecc3a5c1527216447c87d.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/plate-220428-125250_jpg.rf.b134bcb7e4109b15aee484a290e0d4ec.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/rice_27_jpg.rf.1378f08b168523058bdc3e2d66256c8f.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/rice_6_jpg.rf.3fc0c078736f2ab78681d3d52f457fe2.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/youtube-300_jpg.rf.a47c5ff42045a4e5d3a3d1d48759c906.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/test/images/youtube-318_jpg.rf.828603579a857767eacbb3543da15d8a.jpg
   creating: /content/dataset/Food Detection.v2i.yolo26/test/labels/
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/1028_191030_0004_jpg.rf.3f6884ec99e0e58d7b3947b7f6efa5b6.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/1028_191030_0039_jpg.rf.5dbc2837eae3e82740cb39d014b8d991.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/1028_191030_0068_jpg.rf.e8132a3cffab2d6df1c2996c4d73610e.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/1028_191030_0083_jpg.rf.53f8d9917663bd6331f1d1259c7bbc91.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/1028_191030_0092_jpg.rf.09d5c251d283269bb2e7ebfa279773de.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/1030_191030_0010_jpg.rf.982fb28e9b61458b3d57c8e6a891d7b9.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/1031_191103_0039_jpg.rf.040cf89743c5ec91477504b6da2dd9e5.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/1031_191103_0044_jpg.rf.22da80263c4f59716e21c22ab57237ff.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/8_jpg.rf.02a6950c1db69427361979acd1c527fc.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/IMG_4169_jpg.rf.dc4facf39573309af006fa9debfe38f0.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/IMG_4225_jpg.rf.6f4c194dbdfb39bf47b4e26720019b33.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/S__184819718_jpg.rf.dbdfee206092837c81a7b8d370c1103b.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/plate-220427-125120_jpg.rf.803af99ca069e3a5430739f083b9b11b.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/plate-220427-125306_jpg.rf.d1533144a79fa0779bcb3616ac502913.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/plate-220428-123237_jpg.rf.fb43d896e3031671d73f3eaa40f93bdb.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/plate-220428-124823_jpg.rf.2dd1ecdc445ecc3a5c1527216447c87d.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/plate-220428-125250_jpg.rf.b134bcb7e4109b15aee484a290e0d4ec.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/rice_27_jpg.rf.1378f08b168523058bdc3e2d66256c8f.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/rice_6_jpg.rf.3fc0c078736f2ab78681d3d52f457fe2.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/youtube-300_jpg.rf.a47c5ff42045a4e5d3a3d1d48759c906.txt
  inflating: /content/dataset/Food Detection.v2i.yolo26/test/labels/youtube-318_jpg.rf.828603579a857767eacbb3543da15d8a.txt
   creating: /content/dataset/Food Detection.v2i.yolo26/train/
   creating: /content/dataset/Food Detection.v2i.yolo26/train/images/
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0002_jpg.rf.940291866b2aed77aadf3e5c1ed9e5b7.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0002_jpg.rf.a58403d34f14b3c2751bd0ab41ef85ed.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0003_jpg.rf.38e2da11cbc483b7c9018a5e9e17b781.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0003_jpg.rf.c6223271b833b13a812d50981bdf352a.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0007_jpg.rf.96fda01670900c313da764cba3dc5add.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0007_jpg.rf.9f6480f8bb57b831e34919c126c2a04e.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0011_jpg.rf.0f698e9815b9cf73e9137c74f4d824d7.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0011_jpg.rf.9c7c902543a114a33cd6ec37cef35289.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0016_jpg.rf.76116750d76b8d33bd3a9dc1b2e3bde9.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0016_jpg.rf.daabe0933011fc4a4cf376d30cea3c6f.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0023_jpg.rf.7a30948949a939f9ea45d6395b2fec27.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0023_jpg.rf.8bc9adca15c8148bd240de43dc80c4a1.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0023_jpg.rf.af472572e7bf5170ce0016eef64edfa3.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0023_jpg.rf.c79abe0b54ffea2afc87322451f62d5c.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0024_jpg.rf.31a186a3678034eeb825e5620b1a6375.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0024_jpg.rf.baab5be03c74892559cfbe8235d60b21.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0025_jpg.rf.12ef38dd62100a676cd01f84f876020d.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0025_jpg.rf.2736804c6976a155903da9ffb67991c6.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0033_jpg.rf.cfada6c465a1fc06d1fad241ed702c61.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0033_jpg.rf.f07c19125ae3e235ab01de8d86efbc9b.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0041_jpg.rf.5fbcb8cfb31421299b49f5b6bc5440b1.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0041_jpg.rf.8c09a10169c36ce5e38631aaa1fa4880.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0043_jpg.rf.4fb922b0bf288195836426310b46cfd5.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0043_jpg.rf.d8569d9fae068c22d971a72f950340db.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0044_jpg.rf.490dd05f2ec6402640f9866837ea7dc2.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0044_jpg.rf.6dddac4c5c53edb9b585b0fee7f0cdb3.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0050_jpg.rf.47c225b19c20c7e95708a1b701863020.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0050_jpg.rf.799cb08d8f9cf3052857da3dc1d4a95b.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0051_jpg.rf.30f57c2e7de3685ce00fdf52a89f7a22.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0051_jpg.rf.47f928ee2a5f2f2113ca9f457ef2c1f3.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0066_jpg.rf.4e334c86a77095097bba3929fe7af3f3.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0066_jpg.rf.9540164bea5a0722d5ed5f648071f748.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0076_jpg.rf.40c54ef7faa2a6dcb6ca09f3189da0df.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0076_jpg.rf.5627a5305aa5cf5aa511f18c281fd0d1.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0080_jpg.rf.357e0dddf7a3e960224d7b2e555239b5.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0080_jpg.rf.71f9b5f0b31d08364d4261728a69337b.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0084_jpg.rf.9ba2af8e74151725435f4469d2b3c691.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0084_jpg.rf.aec1678fba1aa5bf1c1a1aa767b634ad.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0084_jpg.rf.bc4701267a3a6c254cc29ee01b3e7ddf.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0084_jpg.rf.dafae16ebe16dbc47f9f2cc11772dcea.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0088_jpg.rf.9718e95c619f557073e39886e3b57e2e.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0088_jpg.rf.dbc57d6a4bf0d1d173fdbfaca243a0c9.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0093_jpg.rf.bb633c4e80965736c6f6bb482ba4ee22.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1028_191030_0093_jpg.rf.e9f41c8db05238628527215d359fc753.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0004_jpg.rf.0950cae228aefbf454d88232b2c85c9f.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0004_jpg.rf.761b0186c880c398c228d38f08928496.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0016_jpg.rf.52c1828677dbbc0ab974afcb74bbc940.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0016_jpg.rf.e110aafb7dd3fd2d0f9ea7aaa8d79481.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0034_jpg.rf.4ca9655f478921e7db13f29ce7f592d8.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0034_jpg.rf.b855775ba3e23a5868dbe8774028f8e0.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0035_jpg.rf.683ce3e56512244834ebf6c406e1b1e6.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0035_jpg.rf.ddc397d54746d1f5715b953471e3278d.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0035_jpg.rf.eb1981baa82e66ed15ee44158dd979f0.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1030_191030_0035_jpg.rf.fe0db6f1bee2be638e290607da5e704e.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0005_jpg.rf.55e44117377ee44d5f3fed0ec2a63b3f.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0005_jpg.rf.d62ed516792dbe9a1b65a260decc507d.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0011_jpg.rf.64cd29e823771295e455d2d52efc598e.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0011_jpg.rf.a1ed2b07b0932e9ac56636049a2724b5.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0018_jpg.rf.2e4f30efddd09948ea5adf235d907b63.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0018_jpg.rf.f01234b087c45c7264b1201743c8708b.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0036_jpg.rf.7e605af1aeeff84e3873af5e23194eb5.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0036_jpg.rf.a3f1dba5be490e008f95fc61a4b43c75.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0043_jpg.rf.1e72ed53acb9d872a6068d984bc38403.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0043_jpg.rf.49d400b4cccc6b0f779cfe9e411debdc.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0045_jpg.rf.28e103270f92b26f0cc0355d1da17bbf.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0045_jpg.rf.94d950d136db2e9180d5300ca4519c92.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0055_jpg.rf.1469eb31c655a8f18cbcc2145e94b52d.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0055_jpg.rf.c1dcb16b3308e35d7f692a6b04b477ae.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0056_jpg.rf.5e6604b85e34e92960bfb073a529cdcd.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/1031_191103_0056_jpg.rf.64e24b49750372cb63202a58bc151597.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/10_jpg.rf.74355d03b1c481fb76807ccc5e1626a6.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/10_jpg.rf.944a61dbf98a404f058b7e8f4d5c82dc.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/114_191107_0001_jpg.rf.a1efaed08a3acce447df37f43fa22769.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/114_191107_0001_jpg.rf.ea277b14deb9f8e83520a8b2fb59c020.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/114_191107_0009_jpg.rf.a2f13ae1ddab39e748e541bfe3d58cef.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/114_191107_0009_jpg.rf.c2ab00bde8400c9fc85e8a5de7dc5317.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/114_191107_0023_jpg.rf.85f8623a1030521782bed091a9cc4c85.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/114_191107_0023_jpg.rf.e054ceca0ae8a4e7d65232fe893f511b.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/115_191107_0009_jpg.rf.66ce52c02a0314130f8fdc98c59dbdc8.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/115_191107_0009_jpg.rf.8069cd44a340cfac23277daa9c8c3910.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/17_jpg.rf.266b8eebc92820cc492c7e4ae37e7472.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/17_jpg.rf.a7fa48a6b9b92136141187efd359c60b.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/4_jpg.rf.d6e7cbe7053e54ecfb53c257d867bf99.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/4_jpg.rf.e93a7c07e25732451ab2f43530e3dda8.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_1002_jpg.rf.3fed0c4efb9840b43f6a91bf662d74cf.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_1002_jpg.rf.536cde36fec6ed936df2b3f84dfa69f2.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4175_jpg.rf.a183d5a4a0771ac9f940e14f0d8c66da.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4175_jpg.rf.dbcf79405d9c976d43aff303b37ccc9f.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4178_jpg.rf.c9aebfc8398fbc2e5de21caee7db3f8e.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4178_jpg.rf.d330be8a14b310268fdbd8533c8e1c4c.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4208_jpg.rf.991e7df3dd8e2b4755b7b492a76ff221.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4208_jpg.rf.dd4dc2d97ba6381a5e07d754eac6784e.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4209_jpg.rf.3b706e8d793c1be9f4ca373e793ba94c.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4209_jpg.rf.92cb732c051fa9f100c5687c8b8f05ce.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4210_jpg.rf.164f2f8608e1503844940b4c1cf2c463.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4210_jpg.rf.7432e57988d59c4f9a401214a84b9107.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4220_jpg.rf.5470ed5e164581c08e669ee1a8350bfd.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4220_jpg.rf.a9702ab2b526c34b2cc5afb94ae0f4b2.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4222_jpg.rf.05a5ef859c903d4c9412037076122fc4.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4222_jpg.rf.9b46107ed8d3c3bfee9a30bd10a0fd8f.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4233_jpg.rf.1b82b2ea0d01e0e27e87a32d2eb46610.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_4233_jpg.rf.59576c3ef0801ce92b32efe6f4f6bdc4.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_9162_jpg.rf.0538e27a9f0572638b78ae36c395bb43.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/IMG_9162_jpg.rf.1268368562944d88b159cc0db8bda72e.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/S__184819723_jpg.rf.45268709c4ebd508ce6cf1f30206e32d.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/S__184819723_jpg.rf.5836f6e657853742710e8263e64158c1.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/S__184819723_jpg.rf.b3a68b9d00ab465c245a9ceaa7766ccc.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/S__184819723_jpg.rf.bfc939de3d35507e4b9c25ed421b7e99.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/S__184819723_jpg.rf.d100111e3e4c8ecccdaa4565be17effd.jpg
 extracting: /content/dataset/Food Detection.v2i.yolo26/train/images/S__184819723_jpg.rf.f5cb2f1c84a9537022c9b7c465aa52a6.jpg

In [8]:
!unzip -d "/content/dataset/Food_Detection_Project.v19i.yolo26" "Food_Detection_Project.v19i.yolo26.zip"

Streaming output truncated to the last 5000 lines.
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/cd98b43f19867984_jpg.rf.e2d060e06c3a0d75739b071e5415a995.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/cheese_1021231240534_jpg.rf.3131ca1e2a01fb7b951405a08c7156d3.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/cheese_1201021021_jpg.rf.9b7c7cb40e56988dab1212a80454f5ce.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/cucumber1232_jpeg.rf.ece68785d38f5c3370370622a09fd9e9.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/dbe81f8fd25f53a7_jpg.rf.c728947b4622695a336de25e705d9cfe.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download-1-_augmented_1_jpg.rf.2ee71c0a6f4ba0d99d7eb95952e77b2a.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download-14-_augmented_2_jpg.rf.f7c428af3fcd960688017ddb6749fa77.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download-15-_augmented_1_jpg.rf.c39eaaf791cf1001275f05bfe5fc706d.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download-2-_augmented_2_jpg.rf.813bb4fbc1a98f69a5488a43ab26eebb.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download-5-_jpeg.rf.8c73cf4418ca8c902adc62b9fd1b2d5f.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download-6-_jpeg.rf.b0b4df5b4be591b65a775de6445aaec8.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download-8-_augmented_1_jpg.rf.f932cbad4f7f9ea903f602b7343374cf.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download-9-_augmented_2_jpg.rf.26e45f6fab5550316f2a880a4f3d848a.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/download_augmented_1_jpg.rf.ad6c9c2df17fd687223ffe34da2ed9b3.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/e3ef6bb3fc9c3d48_jpg.rf.b0cdddb4aa752a7bfd5eec3d4154c476.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/e94e6960-d185-4902-bd6f-a7b5dcc8a496_jpg.rf.7e23c82e6b8882f8b9502e179718ac5e.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/ecf88fd8-12db-41a4-8f47-1714ba31bd15_jpg.rf.37ef307bedcd6e91e37b252fa25bbe57.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/eggplant12123_jpg.rf.eeaadff77d3cb9a96b73602ad861d3df.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/eggplant12_jpg.rf.ec3aa34fb84a017cb0b1832917154203.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/eggplant13123_jpg.rf.eb94dc1809863d484d9d6c94fbcdc7b2.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/healthy-1113-_jpg.rf.2578c31973d9849401754da3ea0eefd7.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/healthy-1408-_jpg.rf.2026b104f7804f3d55911310af4b77cf.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/healthy-394-_jpg.rf.cb1579df03957de76f531428a2ec7f91.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/healthy-490-_jpg.rf.460931b39f41dc37d09398d47e90c7fb.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/healthy-534-_jpg.rf.eb9259b4a34badd47b789540c5495ad6.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/how-to-grow-carrots-with-dr_-john-navazio_jpg.rf.117a271b2b083f6b5a3ea6ccb338e74a.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-12-_augmented_1_jpg.rf.188815806276df91655e0b3bac12cb77.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-14-_augmented_2_jpg.rf.590ee2392cb2396033461a086d8422ff.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-14-_augmented_3_jpg.rf.696cf4f13cadcffa1e9b90956b4fe638.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-17-_augmented_3_jpg.rf.dc7736335c4b1e6c336f0b70bcfcdd33.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-17-_jpeg.rf.9997aed628422b54011200485a1306fe.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-18-_augmented_1_jpg.rf.a88d1959f358b19b9ab6f94200f589e2.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-18-_augmented_2_jpg.rf.aa5837f994b6f852c8bc4945726545af.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-22-_jpeg.rf.6674b5f3bf8b4082623c0204ca240e1d.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-43-_jpg.rf.0e799a89e1b2dc244c1a283834fbc8dd.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-49-_jpeg_jpg.rf.5a10f05423af8ddb03f7a320a786b72a.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-5-_jpeg.rf.9d7689951e88c967918e529c16d66aa2.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images-84-_jpg.rf.712b1580e277b3f455c2d1f2dbc0aa35.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/images57_jpg.rf.aa63f9794ce1dce0fd00131ee2cca698.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-1324972373-612x612_jpg.rf.5dbab7d1df5a42f5ca0bf34603e68b9f.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-1326772074-612x612_jpg.rf.47e3b437286d0e01cb43c78992ad86af.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-157281328-612x612_jpg.rf.ec75a3c4d0fe580c440949ca79e0318d.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-461999761-612x612_jpg.rf.c8d75bc3683335859fa7a9e167f4b346.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-463743233-612x612_jpg.rf.5ae0e3a0c388371c25f4d77502af69c8.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-471438145-612x612_jpg.rf.f5198c12e24730ddd27e39f6d7cd2e95.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-534892477-612x612_jpg.rf.8c587d9fa069685b006579f8a522d6d6.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-589967360-612x612_jpg.rf.6344e1d33f06db42cc9f3537f28d7137.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-636178270-612x612_jpg.rf.5b075b7063092230dcf62bee4deb25c4.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-639326958-612x612_jpg.rf.f58c62d6c0858f1b28de9d53bf0788b2.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-941673006-612x612_jpg.rf.c54c06b5dfe66bdd82275fa1ebca2bd9.txt
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/istockphoto-982837618-612x612-1-_jpg.rf.a71b383d6ff3719b673db73d4b3ec134.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/k-c3-a4se-l-c3-b6cher_JPEG.rf.bdb09cacff71c1b5d1a6793d351c6056.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/kaese-lagern.rf.80026415977d1cdb8907da746a622990.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/kaese-lexikon-edamer_03f88728ec_csm.rf.e444f40be58efec6b4f6c54f9010bcd3.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/kaesestuecke-die-richtige-lagerung-von-kaese-ist-wichtig-damit-er-moeglichst-lange-frisch-bleibt-.rf.2156859445da22b5e147b71dfc2c108a.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/kolbasa-krakovskaya_jpg.rf.1751786db66a5083ceb7de8261fd58a9.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/milk12318_jpeg.rf.341598009a480062509473e9ace45a13.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/milk12319_jpeg.rf.4e222d515e77845330d8393321af3521.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/milk12326_jpeg.rf.d9ddbfc91abd23f6bcbe6882c41dad25.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/milk12328_jpeg.rf.a4161457bfc59fda08f24c005af1da94.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/montanaro_kaese-13.rf.3b33de38c77f1de2a566459a781bc01a.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/naver_0133_jpg.rf.7700486fcd74745efaaff3cb8bc661de.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/naver_0170_jpg.rf.4c1494dafa163b1e04eb0bea9cead516.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/naver_0320_jpg.rf.5bde893c5f6081bd4342b39e5b8387c7.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/naver_0341_jpg.rf.d5a024054418fa25b9e83a12b8200bb1.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/naver_0351_jpg.rf.f915eb6efe55c1d40fb7a3e6e3cda4b0.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/naver_0373_jpg.rf.46efeca1d3040a2b7f30079543dfbd48.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/naver_0417_jpg.rf.60b1551c2c323f64bc2b0cf88929a96f.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/naver_0438_jpg.rf.8dd993d7f8c9b3f1d5e8dcd459132df5.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/not_damaged_128_jpg.rf.379d1b881ec414a0c8247edd769bc0fa.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/not_damaged_131_jpg.rf.eeb1837bcade85fbe9a93448713f36dc.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/not_damaged_144_jpg.rf.e8a48041cae20f21e028b7c799511bb2.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/not_damaged_151_jpg.rf.e4fa6504c7d491ba6dcf2711d639b9e7.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/not_damaged_2_jpg.rf.d95ca573d92d72ab9f340a9b209f066c.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/not_damaged_35_jpg.rf.22f8461d7feea9d5aa7f1c2539b4f02d.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/not_damaged_45_jpg.rf.1a2035c45f85458402316c0bae1b71a7.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/not_damaged_52_jpg.rf.5f829b1a51ed53a0d1748a4eef302366.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/patlican13_jpg.rf.64e8ebe0a2b8cfc4bb319a042433a313.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/patlican32_jpg.rf.2606ca0fe58b6e1381be6ef4d83e063a.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/pngtree-cucumber-png-image_5630597_jpg.rf.cea74ddead36844bb15ecffe8a6293b2.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/scale_1200_jpg.rf.4a913dccbc6fd740745d2fdfdc47baa4.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/t_wissensbissen_aufbewahrung_JPEG.rf.8e6e55128d3531a4c85923ba02d14c67.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/three-eggs_jpg.rf.32ee86da10a6e1371d78068ca38f48ce.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/tomato1_30-jpg_0_6740_jpg.rf.e786d8776f726ca1b7bc09191aa35c52.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/tomato_turntable-40_jpg.rf.ca45efead3d71d6e4a36a8d2c2f05797.txt
  inflating: /content/dataset/Food_Detection_Project.v19i.yolo26/test/labels/uriger-allgaeuer-bio-kaese.rf.969a3f4f385f5f77f50f0d2ce024d683.txt
   creating: /content/dataset/Food_Detection_Project.v19i.yolo26/train/
   creating: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-0017_png.rf.b24ae16dbf8777842085029b109a9d5a.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-0072_jpg.rf.26a4996037e0437536d4f51de5f7446b.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-0090_png.rf.0e6cd256dd7a33ebba29d66cc7202278.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-1-__jpeg.rf.9d5f475c372c13898c070b0354da472c.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-1-_jpeg.rf.4fcd8eff7d9efdc8632da50d4cc79d6e.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-1-_jpeg.rf.d92a0fb06447ecbd7d740967f138e07b.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-1-_jpeg.rf.eafb8a2f3d042043b936722a748931aa.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-1-_jpg.rf.a5cf2e9e1ad2cbe2e838aa1745773161.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-100-_jpg.rf.8ef5388f0e32aae1c7c84109df376c40.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10001_jpg.rf.078acba63cf0d6c455cba74079ec4786.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-100_jpg.rf.038758f826fc5e520e740f9bfa410775.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-100_jpg.rf.37884d6951fa1c666d6a2ba7f544c8cb.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-100_jpg.rf.e565e3b31c87550f02574bc596846f5a.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-1010611969_-Cucumber-Half-On-White-Background-Closeup-_-Shutterstock_jpeg.rf.5d2d1079053e759e2925d9107535f1e5.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-101_jpg.rf.0de74343b3ea4bf0c0ac2250d5472a92.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-101_jpg.rf.151a6a7a4f230e35a687f058b8a08d58.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-101_jpg.rf.1b83904261119a1166a427ad8938e758.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-101_jpg.rf.9caf1107af9dbaaf81af998d0a67e31f.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-102_jpeg.rf.1c4dc5cc77ab8bcd8558bd450bfd268a.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-102_jpg.rf.5a0edfdcee6093e5433c89eacbff4b7f.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-102_jpg.rf.f86f300efdfe8c3da66b635c8bccaa9a.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-103_jpg.rf.3d1360490db4aebc76a8d4c5d4c40769.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-103_jpg.rf.4f607f010dede9019302877c1f6df946.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-103_jpg.rf.5d3cd11ddf01cf33344b39885037f7d3.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-103_jpg.rf.5dc4ecffac491e8b1ef5c45bbd405442.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-104_jpg.rf.599738398ddcf5340c67ab8338bc731b.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-104_jpg.rf.b11455de1f220812731d89470c35cb67.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-104_jpg.rf.eebafe78a1fa49b9a1d9fdd0864bba8a.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-105_jpg.rf.57e30c6b1db1451374b37f6931e6eef2.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-105_jpg.rf.dd06922aa0c748041ad42b9cb8732735.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-106_jpeg.rf.a3d269d4f01f04ee227b56fdbed395fb.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-106_jpg.rf.4e7e1b3a0d631cfacd96ca2e28ca4917.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-108_jpg.rf.2de2a1d5b3099347cab2e455e2b9ab26.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-109_jpg.rf.05e9c2612b15dde7eb8b14ed7fa1ace2.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-109_jpg.rf.d1088f788d4f95db6e05ee8f9bcd3a6a.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10_jpg.rf.23d5df3775db539d47037a5654e4746c.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10_jpg.rf.24851b2296e0ea56016f3f646980e9f1.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10_jpg.rf.71c9afb129ba5a4c14edabd193b54021.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10_jpg.rf.7adc12788a3561a97d9374fd88708d1b.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10_jpg.rf.91998879ca9013991af95e80c1d63c81.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10_jpg.rf.9f7c3bb6902eda2b5a2480856dfd162b.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10_jpg.rf.a4224e2325fca55ce9f937108a8c0460.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-10_jpg.rf.be5fb4cc84e3e003f677479c15e37622.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-11000_jpg.rf.d2e4a9853fd6851c52f6e2ca70d20ecc.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-110101_jpg.rf.dcb032043054340b2815810854eea51b.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-110_jpg.rf.20c6d1b4f65a829ed307605f250a24e4.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-110_jpg.rf.97314109d983131386b2b3ff073917ef.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-110_jpg.rf.99844b53f191feb37ecdf9bde9cdf705.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-11112122_JPG.rf.9b929703016d0c76f2f1091b61898ab2.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-111_jpg.rf.97366aa21ba14a3b0c6698a2437473a5.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-111_jpg.rf.c4f87066d1fde0d5c58d74e6fb306ef2.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-111_jpg.rf.f7c9fb92b4035b6e0de821312c868447.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-112_jpg.rf.199dc8b3b823651e9a6fa07a645643b8.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-113_jpg.rf.a5246635c9aa5df6295add734049c326.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-113_jpg.rf.aa371c0457d9628fb6aa7d81fadf6a2a.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-114_jpg.rf.26293249f5d6073d9fe23cb712b54ec8.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-114_jpg.rf.aaec47a0d03ecc7a6f39dd9ba90474d5.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-117_jpeg.rf.858157fe99f52a7101de23c81b9679a3.jpg
 extracting: /content/dataset/Food_Detection_Project.v19i.yolo26/train/images/-117_jpg.rf.ca9609100cfe6554fc70e4b21b3492f3.jpg

Atau update dataset yang sudah ada di W&B

In [5]:
# format --> wandb artifact get "FAIt (Food AI-based tracking)/<nama dataset>:latest" --root /content/dataset/<nama dataset>
#!wandb artifact get "FAIt (Food AI-based tracking)/New_Food_Dataset:latest" --root /content/dataset/New_Food_Dataset

wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: Enter your choice: 2
wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Create a new API key at: https://wandb.ai/authorize?ref=models
wandb: Store your API key securely and do not share it.
wandb: Paste your API key and hit enter:
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Downloading dataset artifact b10g004dicoding-dicoding-batch-10-g004/FAIt (Food AI-based tracking)/New_Food_Dataset:latest
wandb: Downloading large artifact 'New_Food_Dataset:latest', 311.02MB. 6244 files...
wandb:   6244 of 6244 files downloaded.
Done. 00:00:53.3 (5.8MB/s)
wandb: Artifact downloaded to /content/dataset/New_Food_Dataset

In [6]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import yaml
from collections import OrderedDict
import shutil
import requests
from bs4 import BeautifulSoup
import time
from datetime import datetime, timezone
from google.colab import userdata
import wandb

In [7]:
def get_classnames(dataset, dataset_dir='/content/dataset/'):
  with open(dataset_dir + dataset + "/data.yaml", 'r') as file:
    read = yaml.safe_load(file)
    classnames =  read['names']
    return classnames

In [8]:


def dataset_to_df(dataset_dir, classnames, image_dir="/images/", label_dir="/labels/", image_ext=".jpg"):
  rows = []
  le = LabelEncoder()
  le.fit(classnames)

  for train_set in os.listdir(dataset_dir):
    if os.path.isdir(dataset_dir +  train_set):
      for label_file in os.listdir(dataset_dir + train_set + label_dir):
          if not label_file.endswith(".txt"):
              continue

          file_name = os.path.splitext(label_file)[0]
          label_path = os.path.join(dataset_dir + train_set + label_dir, label_file)

          image_path = os.path.join(dataset_dir + train_set + image_dir, file_name + image_ext)

          image_exists = os.path.exists(image_path)

          with open(label_path, "r") as f:
              lines = f.readlines()

          for line in lines:
              line = line.strip()

              # Skip baris kosong
              if not line:
                  continue

              parts = line.split()

              # Minimal harus ada label + bounding box
              if len(parts) < 2:
                  rows.append({
                      "label_path": label_path,
                      "label_name": None,
                      "label": None,
                      "image_path": image_path,
                      "bounding_box": line,
                      "status": 0
                  })
                  continue

              label = int(parts[0])
              label_name = le.inverse_transform([label])[0]
              bounding_box = ' '.join(parts[1:])

              rows.append({
                  "label_path": label_path,
                  "label_name": label_name,
                  "label": label,
                  "image_path": image_path,
                  "bounding_box": bounding_box,
                  "status": 1 if image_exists else 0
              })

  # Buat DataFrame
  df = pd.DataFrame(rows)
  df['label_name'] = df['label_name'].str.lower()
  df['label_name'] = df['label_name'].str.replace('_', ' ')
  return df

In [9]:
def replace_dir(filename, dest):
  fname_split = filename.split('/')
  fname_split.pop(2)
  fname_split[2] = new_dataset_dir
  dest_fname = '/'.join(fname_split)
  dir_fname = '/'.join(fname_split[:-1])
  return dest_fname, dir_fname

In [10]:
def create_dataset_dir(dataset_dir, root='/content/'):
  for train_set in ['/train', '/test', '/valid']:
    for d_type in ['/images', '/labels']:
      new_dir = os.path.join(root + dataset_dir + train_set + d_type)
      if os.path.exists(new_dir) == False:
        os.makedirs(new_dir)

In [11]:
def get_dataset_list(dataset_dir='/content/dataset/'):
  dataset_list = []
  for dataset in os.listdir(dataset_dir):
    if os.path.isdir(dataset_dir + dataset):
      dataset_list.append(dataset)
  return dataset_list

In [12]:
def all_dataset_to_df(datasets_list, dataset_dir='/content/dataset/'):
  df_list = []
  for dataset in datasets_list:
    classnames = get_classnames(dataset )
    df = dataset_to_df(dataset_dir + dataset + "/", classnames)
    df_list.append(df)
  return df_list

In [13]:
def concat_df(df_list):
  combined_df = pd.concat(df_list, axis=0, join='outer', ignore_index=True)
  return combined_df

In [14]:
def get_new_labels(df):
  labeler = LabelEncoder().fit(df['label_name'])
  df['label'] = labeler.transform(df['label_name'])
  return labeler, df

In [15]:
class FlowStyleListDumper(yaml.Dumper):
    def represent_list(self, data):
        # Represent lists in flow style (inline)
        return self.represent_sequence('tag:yaml.org,2002:seq', data, flow_style=True)

    def represent_ordereddict(self, data):
        return self.represent_mapping('tag:yaml.org,2002:map', data)

    def represent_str(self, data): # Added to force quoting of strings
        return self.represent_scalar('tag:yaml.org,2002:str', data, style='"')


def get_yaml_file(new_dataset_dir, labeler, datasets_list, nutri_fail=[]):

  data_yml = OrderedDict({
      "train" : "../train/images",
      "val" : "../valid/images",
      "test": "../test/images",
      "nc" : len(labeler.classes_),
      "names" : labeler.classes_.tolist(),
      "additional": {
          "datasets" : datasets_list,
          "datetime" : datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S'),
          "nutrition fail" : nutri_fail

      }
  })


  # Register the custom representers
  FlowStyleListDumper.add_representer(list, FlowStyleListDumper.represent_list)
  FlowStyleListDumper.add_representer(OrderedDict, FlowStyleListDumper.represent_ordereddict)
  FlowStyleListDumper.add_representer(str, FlowStyleListDumper.represent_str) # Register for string quoting

  with open("/content/" + new_dataset_dir + "/data.yaml", 'w') as file:
      yaml.dump(data_yml, file, Dumper=FlowStyleListDumper, default_flow_style=False, sort_keys=False, width=float('inf'))

In [16]:
def scrape_nutrition_data(query_list, dataset_dir, root="/content/", base_url="https://www.fatsecret.co.id"):
    all_data = []
    base_url = "https://www.fatsecret.co.id"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }

    for item in query_list:
        search_url = f"{base_url}/kalori-gizi/search?q={item}"

        row = {
            'nama makanan': item,
            'kalori': '-',
            'lemak': '-',
            'karbohidrat': '-',
            'protein': '-',
            'satuan': '-',
            'link': '-',
            'status': '0'
        }

        try:
            # ======================
            # 1️⃣ Pencarian
            # ======================
            res = requests.get(search_url, headers=headers)
            soup = BeautifulSoup(res.text, 'html.parser')

            # 🔹 Jika tidak ada hasil pencarian
            if soup.find('div', class_='searchNoResult'):
                print(f"❌ Tidak ditemukan: {item}")
                all_data.append(row)
                continue

            table = soup.find('table', class_='generic searchResult')
            if not table:
                print(f"❌ Tidak ditemukan (table kosong): {item}")
                all_data.append(row)
                continue

            first_link = table.find('a', class_='prominent')
            if not first_link:
                print(f"❌ Tidak ditemukan (link kosong): {item}")
                all_data.append(row)
                continue

            detail_url = base_url + first_link['href']

            # ======================
            # 2️⃣ Masuk halaman detail
            # ======================
            res = requests.get(detail_url, headers=headers)
            soup = BeautifulSoup(res.text, 'html.parser')

            # ======================
            # 3️⃣ Cek link 100 gram
            # ======================
            link_100g = soup.find('a', string=lambda s: s and "100 gram" in s.lower())

            if link_100g and link_100g.get('href'):
                detail_url = base_url + link_100g['href']
                res = requests.get(detail_url, headers=headers)
                soup = BeautifulSoup(res.text, 'html.parser')

            row['link'] = detail_url

            # ======================
            # 4️⃣ Ambil satuan dari div
            # ======================
            serving_div = soup.select_one('div.serving_size.black.serving_size_value')

            if serving_div:
                row['satuan'] = serving_div.text.strip()
            else:
                row['satuan'] = '-'

            # ======================
            # 5️⃣ Ambil nilai gizi
            # ======================
            facts = soup.find_all('td', class_='fact')

            for fact in facts:
                title_el = fact.find('div', class_='factTitle')
                value_el = fact.find('div', class_='factValue')

                if title_el and value_el:
                    title = title_el.text.strip().lower()
                    value = value_el.text.strip()

                    if 'kal' in title:
                        row['kalori'] = value
                    elif 'lemak' in title:
                        row['lemak'] = value
                    elif 'karb' in title:
                        row['karbohidrat'] = value
                    elif 'prot' in title:
                        row['protein'] = value

            if facts:
                row['status'] = '1'
            else:
                print(f"⚠️ Data gizi kosong: {item}")

        except Exception as e:
            print(f"Error pada {item}: {e}")
            row['status'] = 'Error'

        all_data.append(row)
        time.sleep(1.5)

    df = pd.DataFrame(all_data)
    df.to_csv(root + dataset_dir + '/hasil_gizi_100gram.csv', index=False, encoding='utf-8-sig')
    nutri_success, nutri_fail = df[df['status'] == '1'], df[df['status'] == '0']
    return nutri_success, nutri_fail

    print("\nSelesai! Data berhasil disimpan dengan kolom satuan.")


def preprocess_query(query_list):
    cleaned_list = []
    for item in query_list:
        item = item.replace("_", " ")
        item = item.strip()
        cleaned_list.append(item)
    return cleaned_list

In [17]:
def df_to_dataset(df, new_dataset_dir, labeler, datasets_list):
  create_dataset_dir(new_dataset_dir)
  for filenames in df['label_path'].unique():
    curr_df = df.loc[df['label_path'] == filenames]
    image_path = curr_df['image_path'].values[0]

    dest_label, dir_label = replace_dir(filenames, new_dataset_dir)
    curr_df.to_csv(dest_label, sep=' ', columns=['label', 'bounding_box'], header=False, index=False)
    with open(dest_label, 'r+') as f:
        data = f.read().rstrip('\n')
        data = data.replace('"', "")
        f.seek(0)
        f.write(data)
        f.truncate()
    dest_image, dir_image = replace_dir(image_path, new_dataset_dir)
    if os.path.exists(dest_image) == False:
      shutil.copy2(image_path, dest_image)
  daftar_cari = preprocess_query(labeler.classes_.tolist())
  nutri_success, nutri_fail = scrape_nutrition_data(daftar_cari, new_dataset_dir)
  get_yaml_file(new_dataset_dir, labeler, datasets_list, nutri_fail['nama makanan'].tolist())

  return nutri_success, nutri_fail

In [18]:
class WandbHandler:
  def __init__(self, project_name, root='/content/'):
    self.project_name = project_name
    self.root = root
    wandb.login(key=userdata.get('WANDB_API_KEY'))


  def upload_to_wandb(self, dataset_dir):
    artifact = wandb.Artifact(name=dataset_dir, type="dataset")
    artifact.add_dir(self.root + dataset_dir)
    with wandb.init(project=self.project_name, job_type='upload_dataset') as run:
      run.log_artifact(artifact)

  def update_dataset(self, dataset_dir):
    with wandb.init(project=self.project_name, job_type='update_dataset') as run:
      artifact = wandb.Artifact(name=dataset_dir, type="dataset")
      artifact.add_dir(self.root + dataset_dir)
      run.log_artifact(artifact)


  def update_file(self, dataset_dir, file_name):
    with wandb.init(project=self.project_name, job_type='update_file') as run:
      saved_artifact = run.use_artifact(dataset_dir+":latest")
      draft_artifact = saved_artifact.new_draft()

      draft_artifact.remove(saved_artifact.get_entry(file_name))
      draft_artifact.add_file(local_path= self.root + dataset_dir + "/" + file_name, name=file_name)

      draft_artifact.save()

Nama dataset baru, tolong sesuaikan

In [19]:
new_dataset_dir = 'New_Food_Dataset'

In [20]:
wandb_handler = WandbHandler('FAIt (Food AI-based tracking)')

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: b10g004dicoding (b10g004dicoding-dicoding-batch-10-g004) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [21]:
datasets_list = get_dataset_list()

In [22]:
dataset_df_list = all_dataset_to_df(datasets_list)

In [23]:
combined_df = concat_df(dataset_df_list)

In [27]:
new_label, combined_df = get_new_labels(combined_df)

In [28]:
nutri_success, nutri_fail = df_to_dataset(combined_df, new_dataset_dir, new_label, datasets_list)

❌ Tidak ditemukan: cucumber

In [29]:
nutri_fail

   nama makanan kalori lemak karbohidrat protein satuan link status
13     cucumber      -     -           -       -      -    -      0

In [36]:
wandb_handler.upload_to_wandb(new_dataset_dir)

wandb: Adding directory to artifact (/content/New_Food_Dataset)... Done. 5.8s

In [46]:
update = {
    13 : {
    "nama makanan": "cucumber",
    "kalori": 12,
    "lemak": "0,16g",
    "karbohidrat": "2.16g",
    "protein": "0.59g",
    "satuan": "100 gram (g)",
    "link": "https://foods.fatsecret.com/calories-nutrition/usda/cucumber-(peeled)?portionid=59108&portionamount=100.000",
    "status": 1
    }
}

In [47]:
for idx, values in update.items():
    nutri_fail.loc[idx] = values

In [48]:
nutri_fail

,nama makanan,kalori,lemak,karbohidrat,protein,satuan,link,status
13,cucumber,12,"0,16g",2.16g,0.59g,100 gram (g),https://foods.fatsecret.com/calories-nutrition...,1

In [49]:
new_nutri = concat_df([nutri_success, nutri_fail])

In [50]:
new_nutri

,nama makanan,kalori,lemak,karbohidrat,protein,satuan,link,status
0,aw cola,37,"0,02g","9,56g","0,07g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/c...,1
1,beijing beef,60,2g,4g,6g,1 porsi (46 g),https://www.fatsecret.co.id/kalori-gizi/kimbo/...,1
2,black pepper rice bowl,329,"1,21g","72,54g","5,07g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/r...,1
3,burger,258,"7,8g","32,1g","12,8g",1 patty (102 g),https://www.fatsecret.co.id/kalori-gizi/mcdona...,1
4,carrot,192,"9,61g","22,38g","6,27g",1 porsi,https://www.fatsecret.co.id/kalori-gizi/tuku/c...,1
5,carrot eggs,140,9g,1g,13g,1 porsi,https://www.fatsecret.co.id/kalori-gizi/mcdona...,1
6,cheese,60,5g,2g,2g,1 porsi (20 g),https://www.fatsecret.co.id/kalori-gizi/kraft/...,1
7,cheese burger,300,12g,33g,15g,1 porsi (114 g),https://www.fatsecret.co.id/kalori-gizi/mcdona...,1
8,chicken nuggets,297,"18,82g","16,32g","15,59g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/c...,1
9,chicken waffle,280,"8,8g","21,8g","34,2g",1 porsi,https://www.fatsecret.co.id/kalori-gizi/shine-...,1
10,chinese cabbage,527,15g,68g,30g,1 plate,https://www.fatsecret.co.id/kalori-gizi/yellow...,1
11,chinese sausage,100,"4,5g",6g,9g,1 porsi (65 g),https://www.fatsecret.co.id/kalori-gizi/pronas...,1
12,crispy corn,435,11g,50g,34g,1 serving,https://www.fatsecret.co.id/kalori-gizi/yellow...,1
13,curry,90,5g,9g,1g,1 porsi (18 g),https://www.fatsecret.co.id/kalori-gizi/s-b/go...,1
14,egg,140,9g,1g,13g,1 porsi,https://www.fatsecret.co.id/kalori-gizi/mcdona...,1
15,eggplant,436,12g,44g,37g,1 porsi,https://www.fatsecret.co.id/kalori-gizi/health...,1
16,french fries,45,2g,7g,0g,1 porsi (10 g),https://www.fatsecret.co.id/kalori-gizi/sianta...,1
17,fried chicken,368,"23,47g","13,69g","25,49g",1 buah,https://www.fatsecret.co.id/kalori-gizi/a-w/fr...,1
18,fried dumplings,90,3g,12g,3g,1 serving (50 g),https://www.fatsecret.co.id/kalori-gizi/bibigo...,1
19,fried eggs,464,12g,48g,41g,1 porsi,https://www.fatsecret.co.id/kalori-gizi/yellow...,1
20,fried rice,501,19g,43g,40g,1 porsi,https://www.fatsecret.co.id/kalori-gizi/klean-...,1
21,hashbrown,140,8g,18g,2g,1 porsi (58 g),https://www.fatsecret.co.id/kalori-gizi/mcdona...,1
22,honey walnut shrimp,100,"4,5g",14g,2g,1 porsi (20 g),https://www.fatsecret.co.id/kalori-gizi/jetz/s...,1
23,kung pao chicken,484,12g,52g,42g,1 serving,https://www.fatsecret.co.id/kalori-gizi/mad-ab...,1
24,mango chicken pocket,297,"18,82g","16,32g","15,59g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/c...,1
25,milk,60,"3,5g",5g,4g,100 ml,https://www.fatsecret.co.id/kalori-gizi/diamon...,1
26,mozza burger,550,33g,43g,25g,1 porsi (266 g),https://www.fatsecret.co.id/kalori-gizi/a-w/mo...,1
27,mung bean sprouts,60,2g,9g,1g,1 porsi (70 g),https://www.fatsecret.co.id/kalori-gizi/joyday...,1
28,nugget,297,"18,82g","16,32g","15,59g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/c...,1
29,perkedel,143,"7,46g","16,52g","3,05g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/p...,1
30,potato,40,2g,5g,1g,1 kemasan (20 g),https://www.fatsecret.co.id/kalori-gizi/sianta...,1
31,rice,268,"0,3g","59,57g","6,8g","5 sendok makan (212,61 g)",https://www.fatsecret.co.id/kalori-gizi/kfc/ri...,1
32,sausage,100,5g,3g,9g,1 sausage (60 g),https://www.fatsecret.co.id/kalori-gizi/fiesta...,1
33,sprite,45,0g,12g,0g,1/2 cangkir (250 ml),https://www.fatsecret.co.id/kalori-gizi/sprite...,1
34,string bean chicken breast,297,"18,82g","16,32g","15,59g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/c...,1
35,super greens,80,0g,17g,2g,1 porsi (250 ml),https://www.fatsecret.co.id/kalori-gizi/rejuve...,1
36,the original orange chicken,297,"18,82g","16,32g","15,59g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/c...,1
37,tomato,18,"0,2g","3,92g","0,88g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/t...,1
38,tostitos cheese dip sauce,505,"37,27g","1,05g","38,62g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/d...,1
39,triangle hash brown,140,8g,18g,2g,1 porsi (58 g),https://www.fatsecret.co.id/kalori-gizi/mcdona...,1
40,water spinach,441,"15,2g","73,6g",5g,100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/w...,1
41,white steamed rice,329,"1,21g","72,54g","5,07g",100 gram (g),https://www.fatsecret.co.id/kalori-gizi/umum/r...,1
42,cucumber,12,"0,16g",2.16g,0.59g,100 gram (g),https://foods.fatsecret.com/calories-nutrition...,1

In [51]:
new_nutri.to_csv('/content/' + new_dataset_dir + '/hasil_gizi_100gram.csv', index=False, encoding='utf-8-sig')

In [52]:
wandb_handler.update_dataset(new_dataset_dir)

wandb: Adding directory to artifact (/content/New_Food_Dataset)... Done. 6.2s

In [53]:
get_yaml_file(new_dataset_dir, new_label, datasets_list)

In [64]:
wandb_handler.update_file(new_dataset_dir,"data.yaml")